### ISSUE TITLE
catkin_ws setup.bash not found

### ISSUE THREAD

**Issue by jasonhu5** [duckietown/duckietown-cslam#23]
`devel/setup.bash/devel/setup.bash` in following line should be `devel/setup.bash`

https://github.com/duckietown/duckietown-cslam/blob/79c86664502aba4f6a2de686eb9b931ebece4d12/01-graph-optimizer/Dockerfile#L42

**Comment by AmaurX** [comment]
True but it shouldnt stop it from working. I will change it

**Comment by jasonhu5** [comment]
That's right. Just happened to spot that :)
