### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by jasonhu5** [duckietown/duckietown-cslam#24]
The variable should probably be `bag_is_present`.

https://github.com/duckietown/duckietown-cslam/blob/79c86664502aba4f6a2de686eb9b931ebece4d12/01-graph-optimizer/ros/src/pose_graph_builder/scripts/transform_listener_ros.py#L617

**Comment by AmaurX** [comment]
true

**Comment by AmaurX** [comment]
fixed btw
